### Библиотека Numpy

In [8]:
%%time 
# полезная команда для проверки времени работы 

arr = []
n = 10**7
for i in range(n):
    arr.append(i*5)

CPU times: total: 3.14 s
Wall time: 3.23 s


In [1]:
import numpy as np

### Одномерные массивы

In [14]:
a = [1, 2, 3, 4, 5]
b = np.array(a, dtype = 'float64')
b

array([1., 2., 3., 4., 5.])

Автоматическое приведение элементов массива к одному типу (согласно иерархии типов) - неявный каст

In [19]:
a = [1, 2, 'a']
b = np.array(a)

print('Для int: ', type(a[0]), 
      '\nДля str: ', type(b[0]))

Для int:  <class 'int'> 
Для str:  <class 'numpy.str_'>


Если не знаю нужной функции, но понимаю, чего хочу, тогда можно воспользоваться поиском в документации

In [20]:
np.lookfor('mean value of array') 

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.isrealobj
    Return True if x is a not complex type or an array of complex numbers.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Retur

Также можно найти функцию по части ее названия

In [99]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

Количественные характеристики ```ndarray```

In [24]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]], 
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])

print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [27]:
print('len:', len(arr), '- количество элементов по первой оси',
      '\nsize:', arr.size, '- всего элементов в матрице',
      '\nndim:', arr.ndim, '- размерность матрицы',
      '\nshape:', arr.shape, '- количество элементов по каждой оси')

len: 2 - количество элементов по первой оси 
size: 24 - всего элементов в матрице 
ndim: 3 - размерность матрицы 
shape: (2, 3, 4) - количество элементов по каждой оси


Особые случаи

In [54]:
a1 = np.zeros(5, dtype = 'int32') # массив из 0
a2 = np.zeros_like(a1) # массив из 0 размерности и типа данных другого массива
a3 = np.ones(10) # массив из 1
a4 = np.eye(2) # на главной диагонали 1

print(a1)
print(a2)
print(a3)
print(a4)

[0 0 0 0 0]
[0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0.]
 [0. 1.]]


Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`.  
Начало и конец диапазона включаются; последний аргумент - число точек

In [62]:
a = np.linspace(0, 1, 5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [70]:
c = np.linspace(10, 32, 12, dtype = 'int32')

print(c)
print('Шаг равен: ', c[1] - c[0])

[10 12 14 16 18 20 22 24 26 28 30 32]
Шаг равен:  2


Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$

In [ ]:
b = np.logspace(0, 3, 12)

print(b)

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


### Некоторые операции над одномерными массивами

In [78]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [79]:
np.log(a)

array([1.09861229, 1.79175947, 2.19722458, 2.48490665, 2.7080502 ,
       2.89037176, 3.04452244, 3.17805383, 3.29583687, 3.40119738,
       3.49650756])

In [82]:
print(a > b)
print(a == b)
print(a < b)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False False False False False False False False False]


Кванторы ``всеобщности`` - для всех элементов массива что-то верно  
и ``существования`` - для хотя бы одного элемента массива что-то верно
$$\forall$$
$$\exists$$

In [91]:
c = np.arange(0., 20)

print(np.any(c == 0.), np.all(c == 0.)) # кванторы существования и всеобщности

True False


In [93]:
print(b)
print(b.cumsum())

[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[  -2.   -6.  -12.  -20.  -30.  -42.  -56.  -72.  -90. -110. -132.]


Сортировка numpy-массивов

In [97]:
a = np.array([0, -2, 5, 3, 8, 9, 7])

print(np.sort(a)) # не меняет сам массив 
print(a)

a.sort() # меняет

print(a)

[-2  0  3  5  7  8  9]
[ 0 -2  5  3  8  9  7]
[-2  0  3  5  7  8  9]


Объединение массивов

In [98]:
b = np.ones(5)

In [103]:
c = np.hstack((a, b, 5 * b))
c

array([-2.,  0.,  3.,  5.,  7.,  8.,  9.,  1.,  1.,  1.,  1.,  1.,  5.,
        5.,  5.,  5.,  5.])

Расщепление массива

In [116]:
a = np.array([-2, 0, 1, 5, 6, 10, 18]) 
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6]) # до 3-его индекса, от 3 до 5, от 5 до 6, 6-й

print(a)
print(x1)
print(x2)
print(x3)
print(x4)

[-2  0  1  5  6 10 18]
[-2  0  1]
[5 6]
[10]
[18]


Функции ``append``, ``delete``, ``insert`` (не Inplace функции)

In [109]:
print(np.delete(a, [2, 4, 1]))
print(a) # ничего не изменилось в самом массиве

[-2  5 10 18]
[-2  0  1  5  6 10 18]


In [110]:
np.insert(a, 2, [-1, -1]) # как и у простого массива

array([-2,  0, -1, -1,  1,  5,  6, 10, 18])

In [111]:
np.append(a, [2.2, 2.1]) # как и у простого массива

array([-2. ,  0. ,  1. ,  5. ,  6. , 10. , 18. ,  2.2,  2.1])

Немного из индексации

In [114]:
b = a[0:4:2]
b[1] = 100
a # изменилось, так как копия не создавалась

array([ -2,   0, 100,   5,   6,  10,  18])

In [117]:
b = a.copy()
b[1] = 100
print(a) # не изменилось, предварительно создали независимую копию
print(b) 

[-2  0  1  5  6 10 18]
[ -2 100   1   5   6  10  18]


In [119]:
print(a[[5, 3, 1]]) # прикольный вывод значений по индексам, ВАЖНО НЕ ЗАБЫТЬ ПРО СКОБКИ

[10  5  0]


Задание:
- Создать массив чисел от $-4\pi$  до $4\pi $, количество точек 100
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива  
- С помощью ``np.all`` проверить, что все элементы равны единице

In [2]:
L = np.linspace(-4 * np.pi, 4 * np.pi, 100) 
Lsin = np.sin(L) ** 2
Lcos = np.cos(L) ** 2
Lsum = Lsin + Lcos
np.all(L)

# np.all((np.sin(L) ** 2 + np.cos(L) ** 2).round() == 1)

True

### Двумерные массивы

In [4]:
a = np.array([[1, 2], [3, 4]])
print(a.ndim)
print(a.shape)
print(len(a))
print(a.size)

2
(2, 2)
2
4


Меняем размерность массива

In [17]:
b = np.arange(0, 20)
b.reshape(2, 10) # не меняет исходный массив
b.shape = (2, 10) # меняет исходный массив
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

Вытягиваем массив

In [18]:
print(b.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
b = np.zeros((3, 3)) # для матрицы заполненной нулями

In [28]:
b = np.eye(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Передаем определенные числа на главную диагональ

In [30]:
b = np.diag(np.array([1, 2, 3, 4]))
b

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Задание:
cоздать квадратную матрицу размера 8, на главной диаг. арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1, остальные элементы 0

In [49]:
matrix = -1 * np.eye(8)[::-1] + np.diag(np.arange(3, 25, 3)) # в первой части специальный способ задать побочную диагональ
matrix

array([[ 3.,  0.,  0.,  0.,  0.,  0.,  0., -1.],
       [ 0.,  6.,  0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  9.,  0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0., 12., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1., 15.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0., 18.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0., 21.,  0.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0., 24.]])

### Умножение матриц

In [58]:
a = 5 * np.ones((5, 5))
b = np.eye(5) + 1 # меняем главную диагональ

print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [64]:
print(a * b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b)) # так же команда для матричного умножения и не только

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


In [74]:
u = np.linspace(1, 2, 2)
v = np.linspace(4, 8, 3)

print(u)
print(v)

[1. 2.]
[4. 6. 8.]


Функция ```meshgrid()``` создает список массивов координатных сеток для указанных одномерных массивов координатных векторов

In [68]:
x, y = np.meshgrid(u, v) 

print(x, '\n')
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]] 

[[4. 4.]
 [6. 6.]
 [8. 8.]]


### Линейная алгебра

In [80]:
a = np.array([[2, 1], [2, 3]])

print(a)

[[2 1]
 [2 3]]


Считаем определитель матрицы

In [81]:
np.linalg.det(a)

4.0

Находим обратную матрицу

In [98]:
b = np.linalg.inv(a) # с учетом того, что матрица обратима

print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [97]:
c = np.array([[2, 1], [6, 3]])

print(np.linalg.det(c)) # определитель равен 0 -> обратную найти не сможем -> ошибка

0.0
