In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Скалярное произведение векторов

In [4]:
a = [10, 20, 40]
b = [-1, 0, 2]

np.dot(a, b)

70

### Перемножение матриц

In [104]:
a = [[2, 4, 8], [3, 5, 7], [0, 1, 2]]
b = [[0, 2, 7], [1, 4, 9], [5, 3, 2]]

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param second: list of "size" lists, each contains "size" floats
    """
    # create list of lists, not np.array
    L = []
    size = len(first)
    for k in range(size):
        vector = first[k]
        L.append([])
        for i in range(size):
            sum = 0
            for j in range(size):
                sum += vector[j] * second[j][i]
            L[k].append(sum)
    return L

print(no_numpy_mult(a, b))

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """
    # create np.array
    return np.matmul(first, second)

numpy_mult(a, b)

[[44, 44, 66], [40, 47, 80], [11, 10, 13]]


array([[44, 44, 66],
       [40, 47, 80],
       [11, 10, 13]])

### Скалярное произведение

In [108]:
a = [3, 5, 9]
b = [1, 7, 2]

def no_numpy_scalar(v1, v2):
    sum = 0
    for i in range(3):
        sum += v1[i] * v2[i]
    return sum

print(no_numpy_scalar(a, b))

def numpy_scalar (v1, v2):
    return np.dot(v1, v2)

numpy_scalar (a, b)

56


56

### Сумма четных элементов на главной диагонали

In [135]:
matrix = np.arange(2, 18).reshape(4, 4)

def diag_2k(a):
    sum = 0
    for i in range(len(a)):
        if a[i, i] % 2 == 0:
            sum += a[i, i]
    return sum

diag_2k(matrix)

# or

np.sum(np.diag(matrix)[np.diag(matrix) % 2 == 0])

14

### Cumsum()

In [153]:
a = np.array([[1, 2, 3], [4, 5, 6]])

def cumsum(A):
    L = []
    for i in range(len(A)):
        L.append(np.cumsum(A[i]))
    return L

cumsum(a)

# or

np.cumsum(a, axis = 1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

### Склеивание

In [298]:
X = np.array([[100, 200, 300, 400, 500], [1, 2, 3, 4, 5]])

def transform(X, a = 1):
    L = []
    for i in range(len(X)):
        X1 = X[i].copy()
        X1[1::2] = X1[1::2] * 0 + a
        X1[::2] = X1[::2] ** 3
        X1 = X1[::-1]
        L.append(np.hstack((X[i], X1)))
    return np.array(L)

print(transform(X))

# or

X1 = X.copy()
X1[:, 1::2] = 1 # важно указывать : до , - показывает, что ко всем строкам применяем операцию
X1[:, ::2] = X1[:, ::2] ** 3
X1 = X1[:, ::-1]
X1 = np.hstack((X, X1))
X1

[[      100       200       300       400       500 125000000         1
   27000000         1   1000000]
 [        1         2         3         4         5       125         1
         27         1         1]]


array([[      100,       200,       300,       400,       500, 125000000,
                1,  27000000,         1,   1000000],
       [        1,         2,         3,         4,         5,       125,
                1,        27,         1,         1]])

### Кодирование массива